{"uuid": "559486ab-b161-4bb4-a243-3d8e76537ecc", "children": ["8a456eb5-6dd5-4428-a6ea-3a4cf7286a56", "74d32ec7-c389-417c-9fa1-7bc920621025", "b6778178-e8c3-43f5-8ba3-be9fa6c35ad1"], "befores": [{"name": "created_user_id", "status": "failed", "statusDetails": {"message": "AssertionError: Expected status code 200, but got 401\n", "trace": "  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Internal\\automation-framework-master\\testsuites\\api\\test_service_api.py\", line 28, in created_user_id\n    api_setup.validate_response(response, expected_status=200)\n  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Internal\\automation-framework-master\\utils\\service_api\\ServiceAPINew.py\", line 89, in validate_response\n    assert response.status_code == expected_status, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Sending POST request to API", "status": "passed", "parameters": [{"name": "api_url", "value": "'https://companydev.jobeze.com/backend/create-user'"}, {"name": "payload", "value": "{'firstName': 'testing123432', 'lastName': '', 'email': 'admin_two4ax326@gmail.com', 'password': '123456', 'user_role_id': 2, 'under_assigned_user_id': 1881, 'companiesList': [-100], 'companiesBranchList': [{'company_id': 379, 'branches': [-100]}, {'company_id': 378, 'branches': [-100]}, {'company_id': 365, 'branches': [-100]}, {'company_id': 358, 'branches': [-100]}]}"}], "start": 1746424094564, "stop": 1746424095009}, {"name": "Validating API response", "status": "failed", "statusDetails": {"message": "AssertionError: Expected status code 200, but got 401\n", "trace": "  File \"C:\\Internal\\automation-framework-master\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Internal\\automation-framework-master\\utils\\service_api\\ServiceAPINew.py\", line 89, in validate_response\n    assert response.status_code == expected_status, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "response", "value": "<Response [401]>"}, {"name": "expected_status", "value": "200"}], "start": 1746424095009, "stop": 1746424095009}], "start": 1746424094564, "stop": 1746424095040}], "start": 1746424094564, "stop": 1746424095280}